baseurl = "https://zubux.github.io/"
theme = "cocoa-eh-hugo-theme"
builddrafts = true
canonifyurls = true
contentdir = "content"
languageCode = "en-US"
layoutdir = "layouts"
publishdir = "public"
author = "Paris Z"
title = "zuBu's homepage"
disqusshortname = ""
pluralizelisttitles = false

[permalinks]
blog = "blog/:slug/"

[params]
dateform = "Jan 2, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
description = "zuBu's little personal space on the web"
logofile = "img/link.png"
faviconfile = "img/logo.png"
highlightjs = true
progressively = true
lang = "en"
github = "zuBux"
# email = "zubu@zubu.re"
linkedin = "pzoub"
twitter = "pzubu"
