# This is a basic workflow to help you get started with Actions

name: Build website

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
            submodules: 'true'
      
      # Downloads hugo
      - name: Download hugo
        run: |
         wget https://github.com/gohugoio/hugo/releases/download/v0.92.0/hugo_0.92.0_Linux-64bit.tar.gz
         tar xvf hugo_0.92.0_Linux-64bit.tar.gz
         mv hugo /usr/local/bin
         chmod +x /usr/local/bin/hugo
         mkdir public
         ls -la themes/cocoa-eh-hugo-theme

      - name: Build Site
        run: hugo -s .

      # Runs a set of commands using the runners shell
      - name: Install gh cli
        run: |
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          sudo apt update
          sudo apt install gh

      - name: Connect to github
        run: |
          echo $GH_ACCESS_TOKEN > gh_pat
          gh auth login --with-token < gh_pat
          rm gh_pat

      - name: Create PR
        run: |
          gh repo clone https://github.com/zuBux/zuBux.github.io.git
          cd zuBux.github.io/
          git config --global user.email $GH_EMAIL
          git config --global user.name "zuBux"
          git remote set-url origin https://$GH_USER:$GH_ACCESS_TOKEN@github.com/zuBux/zuBux.github.io.git
          git checkout -b new-post
          ls -la $GITHUB_WORKSPACE/public/.
          cp -a $GITHUB_WORKSPACE/public/. .
          git add .
          git commit -a -m "New post"
          git push origin new-post
          gh pr create --head --title "New post" --body "This is a test"
=======
