# This is a basic workflow to help you get started with Actions

name: Build website

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
            submodules: 'true'
      
      # Downloads hugo
      - name: Download hugo
        run: |
         wget https://github.com/gohugoio/hugo/releases/download/v0.92.0/hugo_0.92.0_Linux-64bit.tar.gz
         tar xvf hugo_0.92.0_Linux-64bit.tar.gz
         mv hugo /usr/local/bin
         chmod +x /usr/local/bin/hugo
         mkdir public

      - name: Build Site
        run: | 
         hugo -s .
         mv public /tmp/

      - name: Check out my other private repo
        uses: actions/checkout@master
        with:
          repository: zuBux/zuBux.github.io
          token: ${{ secrets.GH_CLI_PAT }}

      - name: Create PR
        run: |
          git config --global user.email 'zuBux@users.noreply.github.com'
          git config --global user.name "zuBux"
          ls -la /tmp/public/.
          cp -a /tmp/public/. .
          git add .
          git commit -a -m "New post"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          repository: "zuBux/zuBux.github.io"
          github_token: ${{ secrets.GH_CLI_PAT }}
          branch: "main"
